import argparse
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, random_split

# --- MULTI-TASK ARCHITECTURE (THE TWO-HEADED CRNN) ---
class NanoSpeechMTL(nn.Module):
    def __init__(self, num_base_classes=4):
        super().__init__()
        
        self.cnn = nn.Sequential(
            nn.Conv1d(1, 64, kernel_size=7, padding=3), nn.BatchNorm1d(64), nn.ReLU(), nn.MaxPool1d(2),
            nn.Conv1d(64, 128, kernel_size=3, padding=1), nn.BatchNorm1d(128), nn.ReLU(), nn.MaxPool1d(2)
        )
        self.lstm = nn.LSTM(input_size=128, hidden_size=64, num_layers=2, batch_first=True, bidirectional=True, dropout=0.3)
        
        self.base_head = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_base_classes)
        )
        
        self.mod_head = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        x = x[:, :, 200:600] 
        x = self.cnn(x).permute(0, 2, 1)
        lstm_out, (h_n, c_n) = self.lstm(x)
        final_feature = torch.cat((h_n[-2, :, :], h_n[-1, :, :]), dim=1)
        
        base_logits = self.base_head(final_feature)
        mod_logits = self.mod_head(final_feature)
        
        return base_logits, mod_logits

def parse_args():
    parser = argparse.ArgumentParser(description="Step 3: Train Multi-Task CRNN")
    parser.add_argument("--dataset", required=True, help="Path to clean_dataset.pt generated by Step 2")
    parser.add_argument("--epochs", type=int, default=50, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=1024, help="Batch size")
    parser.add_argument("--out_weights", default="nanospeech_mtl_best.pth", help="Output path for the trained model weights")
    return parser.parse_args()

def main():
    args = parse_args()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Initializing Training on {device.type.upper()}...")
    
    print(f"Loading Cleaned Dataset from {args.dataset}...")
    X_all, y_base_all, y_mod_clean = torch.load(args.dataset, weights_only=True)
    
    dataset = TensorDataset(X_all, y_base_all.long(), y_mod_clean)
    train_size = int(0.9 * len(dataset))
    val_size = len(dataset) - train_size
    
    generator = torch.Generator().manual_seed(42)
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size], generator=generator)
    
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)
    
    model = NanoSpeechMTL().to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-2) 
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)
    
    # Imbalance correction
    y_train = y_mod_clean[train_dataset.indices]
    train_pu = y_train.sum().item()
    train_u = len(y_train) - train_pu
    pos_weight = torch.tensor([train_u / (train_pu + 1e-6)]).to(device)
    
    criterion_mod = nn.BCEWithLogitsLoss(pos_weight=pos_weight) 
    criterion_base = nn.CrossEntropyLoss()
    
    lambda_base = 0.5 
    best_val_mod_acc = 0.0 
    
    print("\nBeginning Training Loop...")
    for epoch in range(args.epochs): 
        model.train()
        train_m_acc, train_loss, train_count = 0, 0, 0
        
        for b_X, b_base, b_mod in train_loader:  
            b_X, b_base, b_mod = b_X.to(device), b_base.to(device), b_mod.to(device)
            
            optimizer.zero_grad()
            base_logits, mod_logits = model(b_X) 
            
            loss_mod = criterion_mod(mod_logits, b_mod.unsqueeze(1))
            loss_base = criterion_base(base_logits, b_base)
            loss = loss_mod + (lambda_base * loss_base)
            
            loss.backward()
            optimizer.step()
            
            train_m_acc += ((torch.sigmoid(mod_logits).squeeze() > 0.5) == b_mod).sum().item()
            train_loss += loss.item()
            train_count += b_mod.size(0)
            
        avg_train_loss = train_loss / len(train_loader)
        
        model.eval()
        val_m_acc, val_loss, val_count = 0, 0, 0
        
        with torch.no_grad():
            for b_X, b_base, b_mod in val_loader:
                b_X, b_base, b_mod = b_X.to(device), b_base.to(device), b_mod.to(device)
                base_logits, mod_logits = model(b_X) 
                
                loss_mod = criterion_mod(mod_logits, b_mod.unsqueeze(1))
                loss_base = criterion_base(base_logits, b_base)
                loss = loss_mod + (lambda_base * loss_base)
                
                val_loss += loss.item()
                val_m_acc += ((torch.sigmoid(mod_logits).squeeze() > 0.5) == b_mod).sum().item()
                val_count += b_mod.size(0)
        
        avg_val_loss = val_loss / len(val_loader)
        val_m_acc_pct = 100 * val_m_acc / val_count
        
        scheduler.step(avg_val_loss)
        
        print(f"Epoch {epoch+1:02d} | Train Loss: {avg_train_loss:.3f} | Val Loss: {avg_val_loss:.3f} | Val Mod Acc: {val_m_acc_pct:.2f}%")
        
        if val_m_acc_pct > best_val_mod_acc:
            best_val_mod_acc = val_m_acc_pct
            torch.save(model.state_dict(), args.out_weights)
            print(f"New Best MTL Model! Saved to {args.out_weights}")
            
    print(f"\nMulti-Task Training Complete. Best Validation Mod Accuracy: {best_val_mod_acc:.2f}%")

if __name__ == "__main__":
    main()
